flask_app/python/artes_e_telas/routes.py
from flask import current_app, Blueprint, render_template, url_for, redirect, request, jsonify, session
from flask_login import current_user, login_required
from flask_app import db
from flask_app.python.models import User, Arte, Tela, Modelo, Audio, Background, BackgroundsUpload, Fonte
from flask_app.python.artes_e_telas.utils import generate_tela_animation, get_mask, get_discount, sort_model_by_nome
from flask_app.python.users.decorators import customers_only
from flask_app.python.users.utils import get_seed
from flask_app.python.main.routes import download_file
from flask_app.python.ecommerce.utils import woo_object

from sqlalchemy.orm.session import make_transient
from sqlalchemy import desc
import os
import uuid
import subprocess
import multiprocessing as mp
import numpy as np
from PIL import Image
from io import BytesIO
from datetime import datetime
from google.cloud import storage
import pathlib
import shutil
import cv2
import random
import requests

artes_e_telas = Blueprint('artes_e_telas', __name__)


@artes_e_telas.route('/artes_finalizadas', methods=['GET'])
@login_required
@customers_only
def artes_finalizadas():
    user_id = current_user.id

    artes = Arte.query.filter_by(user_id=user_id).order_by(
        desc(Arte.data_ultima_edicao))
    artes = [arte.serialize for arte in artes]

    return render_template('artes_finalizadas.html', title='Galeria de Artes', artes_finalizadas=artes)


@artes_e_telas.route('/editar_tela', methods=['GET'])
@login_required
@customers_only
def editar_tela():
    user = User.query.filter(User.id == current_user.id).first()
    tela_id = int(request.args.get("tela_id"))
    tela = Tela.query.get(tela_id)
    if tela:
        arte = Arte.query.get(tela.arte_id)
        if arte:
            if arte.user_id == current_user.id:
                cores = current_app.config["CORES"]
                fontes = Fonte.query.all()
                fontes_nomes = [fonte.nome for fonte in fontes]

                modelos = Modelo.query.filter(
                    Modelo.id >= 0).order_by(Modelo.nome).all()
                modelos = [modelo.serialize for modelo in modelos]
                modelos.sort(key=sort_model_by_nome)

                if tela.modelo_id >= 0:
                    for i in range(len(modelos)):
                        if modelos[i]["id"] == tela.modelo_id:
                            if tela.cores:
                                modelos[i]["cores"] = tela.cores.split(',')
                            if tela.fontes:
                                modelos[i]["fontes"] = tela.fontes.split(',')
                            modelo = modelos[i]
                else:
                    modelo = {}

                if tela.fundo_id:
                    if tela.fundo_tipo=='uploads':
                        fundo = BackgroundsUpload.query.get(tela.fundo_id).serialize
                    else:
                        fundo = Background.query.get(tela.fundo_id).serialize
                else:
                    fundo = {}

                tela = tela.serialize
                arte = arte.serialize

                return render_template('editar_tela.html', title='Edição de Tela', cores=cores, fontes=fontes_nomes,  modelos=modelos, tela=tela, modelo=modelo, fundo=fundo, background_cfg=current_app.config["FUNDOS_CFG"], woo_active=user.woo_active)
    return render_template('errors/404.html', title='Erro 404')


@artes_e_telas.route('/get_woo_product', methods=['POST'])
def get_woo_product():
    if request.method == 'POST':
        data = request.get_json()

        produto_sku = str(data['sku'])
        user = User.query.filter(User.id == current_user.id).first()

        wcapi = woo_object(user)
        response = wcapi.get(f"products?sku={produto_sku}").json()

        if len(response) > 0:
            produto = response[0]

            data = {}
            data['nome_produto'] = produto['name']
            if produto.get('images'):
                image = produto['images'][0]['src']
                data['imagem_produto'] = image
            if produto['sale_price']:
                data['preco_desconto'] = produto['sale_price']
                data['preco_normal'] = produto['regular_price']
            else:
                data['preco_desconto'] = produto['regular_price']
                data['preco_normal'] = ''
        else:
            data = {}

        return jsonify(data)


@artes_e_telas.route('/add_arte', methods=['POST'])
def add_arte():
    if request.method == 'POST':
        data = request.get_json()

        art_name = str(data['art_name'])
        if art_name == "":
            art_name = "Sem nome"

        arte = Arte(nome=art_name, user_id=current_user.id,
                    data_ultima_edicao=datetime.now())
        db.session.add(arte)
        db.session.commit()

        arte_id = arte.id

        return jsonify({'arteId': arte_id})


@artes_e_telas.route('/get_fundos', methods=['POST'])
def get_fundos():
    if request.method == 'POST':
        data = request.get_json()

        file_type = data['file_type']
        tab_id = data['tab_id']
        pagina = data['pagina']

        per_page = 12
        if file_type == 'videos':
            if tab_id == "todos":
                fundos = Background.query.filter(
                    Background.tipo == 'videos').order_by(Background.id).all()
                num_fundos = len(fundos)
                random_fundos_order = list(range(num_fundos))
                random.Random(get_seed()).shuffle(random_fundos_order)
                pagina_posicoes = random_fundos_order[(
                    pagina - 1)*per_page: pagina*per_page]
                fundos = [fundos[i] for i in pagina_posicoes]
                paginas_total = num_fundos//per_page + \
                    1 if (num_fundos % per_page) else num_fundos//per_page
            else:
                paginacao = Background.query.filter(
                    Background.section == tab_id, Background.tipo == 'videos').paginate(pagina, per_page, error_out=False)
                paginas_total = paginacao.pages
                fundos = paginacao.items
        elif file_type == 'imagens':
            if tab_id == "todos":
                fundos = Background.query.filter(
                    Background.tipo == 'imagens').order_by(Background.id).all()
                num_fundos = len(fundos)
                random_fundos_order = list(range(num_fundos))
                random.Random(get_seed()).shuffle(random_fundos_order)
                pagina_posicoes = random_fundos_order[(
                    pagina - 1)*per_page: pagina*per_page]
                fundos = [fundos[i] for i in pagina_posicoes]
                paginas_total = num_fundos//per_page + \
                    1 if (num_fundos % per_page) else num_fundos//per_page
            else:
                paginacao = Background.query.filter(
                    Background.section == tab_id, Background.tipo == 'imagens').paginate(pagina, per_page, error_out=False)
                paginas_total = paginacao.pages
                fundos = paginacao.items
        elif file_type == 'uploads':
            paginacao = BackgroundsUpload.query.filter(
                    BackgroundsUpload.user_id == current_user.id).paginate(pagina, per_page, error_out=False)
            paginas_total = paginacao.pages
            fundos = paginacao.items

        fundos = [fundo.serialize for fundo in fundos]

        return jsonify({'fundos': fundos, 'paginasTotal': paginas_total, 'paginaAtual': pagina})

@artes_e_telas.route('/fundo_upload', methods=['POST'])
def fundo_upload():
    if request.method == 'POST':
        storage_client = storage.Client(project='rapiartapp')
        bucket = storage_client.get_bucket('rapiart_bucket')

        fundo_upload_image_path = f'storage/user_{current_user.id}/fundo_{str(uuid.uuid4())}.png'
        full_fundo_upload_image_path = os.path.join(
            current_app.root_path, fundo_upload_image_path)
        os.makedirs(os.path.dirname(
            full_fundo_upload_image_path), exist_ok=True)

        f = request.files.get('uploadedImage')
        fundo_upload_bytes = f.read()
        fundo_upload = Image.open(BytesIO(fundo_upload_bytes))
        fundo_upload = fundo_upload.resize((800, 800), Image.ANTIALIAS)
        fundo_upload.save(full_fundo_upload_image_path)

        new_blob = bucket.blob(fundo_upload_image_path)
        new_blob.upload_from_filename(full_fundo_upload_image_path)
        
        bkg = BackgroundsUpload(
            user_id=current_user.id,
            gif=fundo_upload_image_path,
            video=fundo_upload_image_path,
            imagem=fundo_upload_image_path,
            section='imagens',
            tipo='uploads',
        )
        db.session.add(bkg)
        db.session.commit()

        return jsonify({'status': 'success'})

@artes_e_telas.route('/rascunhos', methods=['GET'])
@login_required
@customers_only
def rascunhos():
    arte_id = request.args['arteId']

    if arte_id:
        arte = Arte.query.filter(Arte.id == arte_id).first()

        if arte:
            telas = Tela.query.filter_by(
                arte_id=arte_id).order_by(Tela.posicao).all()
            audios = Audio.query.all()
            arte = arte.serialize
            telas = [tela.serialize for tela in telas]
            audios = [audio.serialize for audio in audios]

            return render_template('rascunhos.html', title='Edição de Arte', arte=arte, telas=telas, audios=audios)

    return render_template('errors/404.html', title='Erro 404')


@artes_e_telas.route('/excluir_tela', methods=['POST'])
def excluir_tela():
    if request.method == 'POST':
        storage_client = storage.Client(project='rapiartapp')
        bucket = storage_client.get_bucket('rapiart_bucket')

        data = request.get_json()

        tela_id = int(data['telaId'])
        arte_id = int(data['arteId'])

        tela = db.session.query(Tela).get(tela_id)
        tela_imagem = tela.imagem_preview

flask_app/python/payments/routes.py
from flask import Blueprint, current_app, jsonify, render_template, url_for, redirect, request
from flask_login import current_user, login_required
from flask_app.python.users.utils import customer_status
from flask_app.python.users.decorators import customers_only, no_customers_only
from flask_app.python.main.utils import send_email_html
from flask_app.python.payments.utils import (
    checkout_done, deleted_subscription_webhook_signal,
    cancel_subscription_at_stripe, reactivate_subscription_at_stripe,
    get_product_info, update_subscription_webhook_signal
)
import stripe

payments = Blueprint('payments', __name__)


@payments.route("/subscribe")
@login_required
@no_customers_only
def subscribe():
    prods_info = []
    for plano in current_app.config['PLANS_DICT']:
        prods_info.append(
            get_product_info(
                prod_id=current_app.config['PLANS_DICT']['prod_id'],
                stripe_id=current_app.config['PLANS_DICT']['stripe_id']
                )
            )
    customer_info = customer_status(current_user.id)
    return render_template("subscribe.html", title='Assinar plano', prods_info=prods_info, customer_info=customer_info)


@payments.route("/cancel_subscription")
@login_required
@customers_only
def cancel_subscription():
    customer_info = customer_status(current_user.id)
    return render_template("cancel_subscription.html", title='Cancelar assinatura', customer_info=customer_info)


@payments.route("/cancel_subscription_action", methods=['GET', 'POST'])
@login_required
@customers_only
def cancel_subscription_action():
    if request.method == 'GET':
        customer_info = cancel_subscription_at_stripe(current_user.id)
        send_email_html(
            email=current_user.email,
            title='Assinatura Cancelada',
            template=render_template(
                'email_cancelsub.html',
                title="Cancelar Assinatura",
                customer_info=customer_info
            )
        )
    return redirect(url_for("users.account", _anchor="assinatura"))


@payments.route("/reactivate_subscription", methods=['GET', 'POST'])
@login_required
@customers_only
def reactivate_subscription():
    if request.method == 'GET':
        customer_info = reactivate_subscription_at_stripe(current_user.id)
        send_email_html(
            email=current_user.email,
            title='Assinatura Reativada',
            template=render_template(
                'email_reactivesub.html',
                title="Reativar Assinatura",
                customer_info=customer_info
            )
        )
    return redirect(url_for("users.account", _anchor="assinatura"))


@payments.route("/config")
@login_required
def get_publishable_key():
    stripe_config = {
        "publicKey": current_app.config['STRIPE_KEYS']['PUBLISHABLE_KEY'],
        "prod_id": current_app.config['PLANS_DICT']['prod_id'],
        "stripe_id": current_app.config['PLANS_DICT']['stripe_id']
    }
    return jsonify(stripe_config)


@payments.route('/customer-portal', methods=['GET', 'POST'])
@login_required
def customer_portal():
    session = stripe.billing_portal.Session.create(
        customer=current_user.customer_id,
        return_url=url_for('users.account', _external=True),
    )
    return redirect(session.url)


@payments.route("/create-checkout-session", methods=['GET', 'POST'])
@login_required
def create_checkout_session():
    price_id = request.args.get('price_id')
    prod_id = request.args.get('prod_id')

    product = stripe.Product.retrieve(prod_id)
    customer_info = customer_status(current_user.id)
    if customer_info=="No customer":
        customer_id = None
    else:
        customer_id = current_user.customer_id
    
    subscription_id = current_user.subscription_id
    if (subscription_id == None) or (subscription_id == "No subscription"):
        subscription_data = {'trial_period_days': product['metadata']['trial_period']}
    else:
        subscription_data = {}

    try:
        print('creating checkout')
        checkout_session = stripe.checkout.Session.create(
            success_url=url_for('payments.payment_done', _external=True) + "?session_id={CHECKOUT_SESSION_ID}",
            cancel_url=url_for('payments.subscribe', _external=True),
            payment_method_types=["card"],
            customer=customer_id,
            mode="subscription",
            allow_promotion_codes=True,
            subscription_data=subscription_data,
            line_items=[
                {
                "description": product['description'],
                "price": price_id,
                "quantity": '1'
                }
            ],
            metadata={
                'user_id': current_user.id
            }
        )
        return jsonify({"sessionId": checkout_session["id"]})
    except Exception as e:
        print('Error:', e)
        return jsonify(error=str(e)), 403


@payments.route("/payment_done")
@login_required
def payment_done():
    try:
        session_id = request.args.get('session_id')
        session = stripe.checkout.Session.retrieve(session_id)
        checkout_done(session)
        customer_info = customer_status(current_user.id)
        if customer_info is None:
            return redirect(url_for('payments.subscribe'))

        send_email_html(
            email=current_user.email,
            title='Assinatura Confirmada',
            template=render_template(
                'email_checkout.html',
                title="Checkout",
                customer_info=customer_info
            )
        )
        return render_template('payment_done.html', title='Pagamento confirmado', customer_info=customer_info)
    except:
        return redirect(url_for('users.account'))


### WEBHOOK
@payments.route("/webhook", methods=["POST"])
def stripe_webhook():
    payload = request.get_data(as_text=True)
    sig_header = request.headers.get("Stripe-Signature")

    try:
        event = stripe.Webhook.construct_event(payload, sig_header, current_app.config['STRIPE_KEYS']['ENDPOINT_KEY'])

    except ValueError as e:
        # Invalid payload
        return "Invalid payload", 400
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return "Invalid signature", 400

    if event["type"] == "checkout.session.completed":
        session = event["data"]["object"]
        checkout_done(session)

    if event["type"] == "customer.subscription.deleted":
        session = event["data"]["object"]
        deleted_subscription_webhook_signal(session)

    if event["type"] == "customer.subscription.updated":
        session = event["data"]["object"]
        update_subscription_webhook_signal(session)

    print(event["type"])
    return "Success", 200

flask_app/templates/account.html
{% extends "base.html" %}
{% block head %}
<link href="{{ url_for('static', filename='css/account.css') }}" rel="stylesheet">
{% endblock head%}

{% block content %}
<div class="div-tabs">
    <ul class="nav nav-tabs">
        <li class="nav-item"><a class="nav-link active" href="#usuario" data-toggle="tab">Usuário</a></li>
        <li class="nav-item"><a class="nav-link" href="#assinatura" data-toggle="tab">Assinatura</a></li>
        <li class="nav-item"><a class="nav-link" id="tab-integracoes" href="#integracoes" data-toggle="tab">Integrações</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="usuario">
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="mb-3">
                        {{ form.username.label(class="form-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span> {{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control") }}
                        {% endif %}
                        
                    </div>
                    <div class="row">
                        <div class="col-sm">
                            <div class="mb-3">
                                {{ form.cpf.label(class="form-control-label") }}
                                {% if form.cpf.errors %}
                                    {{ form.cpf(class="form-control is-invalid", id="cpf") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.cpf.errors %}
                                            <span> {{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.cpf(class="form-control", id="cpf") }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-sm">
                            <div class="mb-3">
                                {{ form.celular.label(class="form-control-label") }}
                                {% if form.celular.errors %}
                                    {{ form.celular(class="form-control is-invalid", id="celular") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.celular.errors %}
                                            <span> {{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.celular(class="form-control", id="celular") }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        {{ form.email.label(class="form-control-label", readonly="readonly") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control is-invalid", readonly="readonly") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span> {{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control", readonly="readonly") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="me-2 mb-2">
                    <p class="dica">Dica: Mantenha seus sempre dados atualizados</p>          
                </div>          
                <div class="me-2 mb-5">
                    {{ form.submit(class="btn-sm btn-general me-2") }}
                </div>
            </form> 
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form2.hidden_tag() }}
                <fieldset class="form-group">
                    <p>Altere sua senha e mantenha sua conta protegida</p>
                    <div class="row">
                        <div class="col-sm">
                            <div class="mb-3">
                                {{ form2.old_password.label(class="form-control-label") }}
                                {% if form2.old_password.errors %}
                                    {{ form2.old_password(class="form-control is-invalid", id="old_password") }}
                                    <div class="invalid-feedback">
                                        {% for error in form2.old_password.errors %}
                                            <span> {{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form2.old_password(class="form-control", id="old_password") }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-sm">
                            <div class="mb-3">
                                {{ form2.new_password.label(class="form-control-label") }}
                                {% if form2.new_password.errors %}
                                    {{ form2.new_password(class="form-control is-invalid", id="new_password") }}
                                    <div class="invalid-feedback">
                                        {% for error in form2.new_password.errors %}
                                            <span> {{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form2.new_password(class="form-control", id="new_password") }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-sm">
                            <div class="mb-3">
                                {{ form2.confirm_new_password.label(class="form-control-label") }}
                                {% if form2.confirm_new_password.errors %}
                                    {{ form2.confirm_new_password(class="form-control is-invalid", id="confirm_new_password") }}
                                    <div class="invalid-feedback">
                                        {% for error in form2.confirm_new_password.errors %}
                                            <span> {{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form2.confirm_new_password(class="form-control", id="confirm_new_password") }}
                                    {% endif %}
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="me-2 mb-5">
                    {{ form2.submit2(class="btn-sm btn-general me-2") }}
                </div>
            </form> 
        </div>
        <div class="tab-pane fade" id="integracoes">
            <div class="content-section">
                <h4>WooCommerce</h4>
                <div class="woo-commerce-form mt-3">
                  <form method="POST" id="woo-commerce-form" action="">
                    <div class="mb-3">
                      <label for="wooCommerceURLInput" class="form-label">URL da loja</label>
                      <input type="url" class="form-control" required id="wooCommerceURLInput" name="woo_url" placeholder="https://www.meuecommerce.com.br">                  
                    </div>
                    <div class="mb-3">
                      <label for="wooCommerceKeyInput" class="form-label">Chave da API</label>
                      <input type="text" class="form-control" required id="wooCommerceKeyInput" name="woo_key" placeholder="ck_...">                      
                    </div>
                    <label for="wooCommerceSecretInput" class="form-label">Secret da API</label>
                    <div class="input-group mb-3">
                      <input type="password" class="form-control" required name="woo_secret" id="wooCommerceSecretInput" placeholder="cs_...">
                      <button type="button" class="btn-sm btn-outline-secondary" style="border-top-right-radius: 5px;border-bottom-right-radius: 5px;" id="button-see-pass" onclick="showWooPassword()"><i class="fas fa-eye"></i></button>
                    </div>
                    <div class="text-center">
                        <div  class="mb-2">
                            <p id='woo-response'>
                            </p>
                        </div>
                        <div class="d-flex justify-content-center">
                            <a href="javascript:void(0)" class="btn-sm btn-general-2 m-3" id="salvar-btn">Salvar </a>
                            <a href="javascript:void(0)" class="btn-sm btn-general-2 m-3" id="salvar-disabled-btn">Salvar <span class="spinner-border spinner-border-sm" id="register-spinner" role="status" aria-hidden="true"></span></a>
                            <a href="javascript:void(0)" class="btn-sm btn-general m-3" id="checar-btn">Checar conexão </a>
                            <a href="javascript:void(0)" class="btn-sm btn-general m-3" id="checar-disabled-btn">Checar conexão <span class="spinner-border spinner-border-sm" id="register-spinner" role="status" aria-hidden="true"></span></a>
                        </div>
                    </div>
                  </form>
                  <p class="text-muted text-center">
                    Não sabe a chave e o secret do seu WooCommerce? 
                    <a href="https://woocommerce.github.io/woocommerce-rest-api-docs/?python#rest-api-keys" target="_blank">Clique aqui</a>
                     e siga as instruções
                  </p>
                  <div class="border-top pt-3">   
                  </div>
                </div>
              </div>
        </div>
        <div class="tab-pane fade" id="assinatura">
            {% if customer_info.status=='active' or customer_info.status=='trialing' %}
                <div class="div-plano mb-2">
                    <h4 class="alert-heading">{{ customer_info.plan }}</h4>
                    <p>Sua assinatura encontra-se ATIVA.</p>
                    <hr>
                    <p class="mb-0">Assinado em: {{ customer_info.start_date }} </p>
                    <hr>
                    <p class="mb-0">Vencimento: {{ customer_info.current_period_end }} </p>
                    {% if customer_info.cancel_at_period_end == False %}
                        <p class="fs-8 mb-0">Renovação automática</p>
                    {% endif %}
                    <hr>
                    <p id="plan_cost" class="mb-0">{{ customer_info.amount }}</p>
                </div>
                {% if customer_info.cancel_at_period_end == True %}
                    <div class="alert alert-warning" role="alert">
                        <p class="mb-0 text-bold">Renovação automática cancelada.</p>
                        <p class="mb-0">A partir de {{ customer_info.current_period_end }} sua inscrição será cancelada e você não poderá criar novas artes.</p>
                        <p class="mb-0">As cobranças estão suspensas para essa conta.</p>
                    </div>  
                    <div>
                        <p>Mudou de ideia? Clique no botão abaixo e reative sua conta sem cobranças extras.</p>
                        <a class="btn-sm btn-general btn-reativar" href="{{ url_for('payments.reactivate_subscription') }}">Reativar renovação automática</a>
                    </div>   
                {% else %}               
                    <div class="mt-3">
                        <a class="btn-sm btn-general-cancel" href="{{ url_for('payments.cancel_subscription') }}">Cancelar</a>
                        <a class="btn-sm btn-general me-2" href="{{ url_for('payments.customer_portal') }}">Editar Assinatura</a>
                    </div>
                {% endif %}

            {% else %}
                <div class="alert alert-warning" role="alert">
                    <h4 class="alert-heading">Que pena!</h4>
                    <hr>
                    <p>Não encontramos planos ativos para seu usuário. Se inscreva e teste grátis nossa ferramenta por 30 dias.</p>
                    <p>Se não gostar é só cancelar sem custos, ok?</p>
                    <a class="btn btn-outline-secondary me-2" href="{{ url_for('payments.subscribe') }}">Assinar</a>                        
                </div>                
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
<script src="{{ url_for('static', filename='js/account.js') }}" type="text/javascript"></script>
{%endblock footer %}

flask_app/templates/email_checkout.html
{% extends "email_base.html" %}
{% block content %}

<p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 20px;">
  Olá {{ current_user.username }},
  <br><br>
  Agora você é um assinante da RapiArt.
  Seu pagamento já foi confirmado e seu usuário já tem acesso a nossas funcionalidades.
</p>
{% endblock content %}

{% block buttons %}
<a href="{{ url_for('users.account', _external=True) }}" style="font-size: 14px; font-family: Helvetica, Arial, sans-serif; text-decoration: none; border-radius: 4px; line-height: 20px; display: inline-block; font-weight: normal; white-space: nowrap; background-color: #6200f5ff; color: #ffffff; padding: 8px 12px; border: 1px solid #6200f5ff;">
  Ver resumo do plano
</a>
<a href="{{ url_for('artes_e_telas.artes_finalizadas', _external=True) }}" style="margin-left: 10px; margin-top: 15px; font-size: 14px; font-family: Helvetica, Arial, sans-serif; text-decoration: none; border-radius: 4px; line-height: 20px; display: inline-block; font-weight: normal; white-space: nowrap; background-color: #d800c6ff; color: #ffffff; padding: 8px 12px; border: 1px solid #d800c6ff;">
  Começar a criar
</a>
{% endblock buttons %}